DROP TABLE IF EXISTS listings CASCADE;

CREATE TABLE listings {
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  photo VARCHAR(255),
  created_at DATE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE ,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
}
